// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_puertorico_mvvm/test/presentation/bloc/government_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_puertorico_mvvm/data/models/government_response.dart'
    as _i3;
import 'package:flutter_puertorico_mvvm/domain/repositories/repository.dart'
    as _i2;
import 'package:flutter_puertorico_mvvm/domain/usecases/get_government_data.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRepository_0 extends _i1.SmartFake implements _i2.Repository {
  _FakeRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGovernmentResponse_1 extends _i1.SmartFake
    implements _i3.GovernmentResponse {
  _FakeGovernmentResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetGovernmentData].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetGovernmentData extends _i1.Mock implements _i4.GetGovernmentData {
  MockGetGovernmentData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Repository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.Repository);

  @override
  _i5.Future<_i3.GovernmentResponse> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<_i3.GovernmentResponse>.value(
              _FakeGovernmentResponse_1(this, Invocation.method(#call, [])),
            ),
          )
          as _i5.Future<_i3.GovernmentResponse>);
}
